name       : dsp
version    : '1.6'
release    : 5
source     :
    - https://github.com/bmc0/dsp/archive/v1.6.tar.gz : 3a4548c185c08dc98dc1090c7762a13f8795b62d3842b744c762c3453fdcaa54
license    :
    - ISC
    - LGPL-2.1
    - GPL-2.0
component  : multimedia.audio
summary    : An audio processing program with an interactive mode
description: |
    dsp is an audio processing program with an interactive mode
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(ao)
    - pkgconfig(fftw3)
    - pkgconfig(libavcodec)
    - pkgconfig(libpulse)
    - pkgconfig(mad)
    - pkgconfig(sndfile)
    - ladspa-devel
setup      : |
    # The default configure macro contains unsupported options
    ./configure --prefix=/usr --libdir=/lib64 --mandir=/share/man --datadir=/share
build      : |
    %make
install    : |
    %make_install
