name       : dsp
version    : 1.3
release    : 1
source     :
    - https://github.com/bmc0/dsp/archive/v1.3.tar.gz : 39c527126ed4c173b3fbc79f0be83e60ba0901e1d0b61b6e30f24b019acfd882
license    :
    - ISC
    - LGPL-2.1
    - GPL-2.0
component  : multimedia.audio
summary    : An audio processing program with an interactive mode
description: |
    dsp is an audio processing program with an interactive mode
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(sndfile)
    - pkgconfig(libavcodec) 
    - pkgconfig(alsa)
    - pkgconfig(ao)
    - libmad-devel
    - pkgconfig(libpulse)
    - ladspa-devel
    - libtool-devel
setup      : |
    # The default configure macro contains unsupported options
    ./configure --prefix=/usr --libdir=/lib64 --mandir=/share/man --datadir=/share
build      : |
    %make
install    : |
    %make_install
